<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1531136203855" stop="1531136217416" version="1.5.2" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default Suite : AutoTestWeb</name>
    <title>Default Suite : AutoTestWeb</title>
    <test-cases>
        <test-case start="1531136207665" stop="1531136216193" status="passed">
            <name>loginAsExistingUser[Testing123@testmail.com,s3cur3P4ssw0rd]</name>
            <description>Registering a new user at Automation Practice</description>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="AutoTestWeb"/>
                <label name="testClass" value="Journey1.loginExistingUser"/>
                <label name="testMethod" value="loginAsExistingUser"/>
                <label name="testId" value="RegNew1"/>
                <label name="host" value="ISVGRELT0002689"/>
                <label name="thread" value="11444@ISVGRELT0002689.TestNG-PoolService-0(15)"/>
            </labels>
        </test-case>
        <test-case start="1531136207665" stop="1531136216217" status="failed">
            <name>loginAsExistingUser[failing@test.com,fail]</name>
            <description>Registering a new user at Automation Practice</description>
            <failure>
                <message>ComparisonFailureWithCause: expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;</message>
                <stack-trace>expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;
	at Journey1.loginExistingUser.loginAsExistingUser(loginExistingUser.java:32)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="AutoTestWeb"/>
                <label name="testClass" value="Journey1.loginExistingUser"/>
                <label name="testMethod" value="loginAsExistingUser"/>
                <label name="testId" value="RegNew1"/>
                <label name="host" value="ISVGRELT0002689"/>
                <label name="thread" value="11444@ISVGRELT0002689.TestNG-PoolService-1(16)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
