<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1530881398059" stop="1530881416595" version="1.5.2" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Default Suite : AutoTestWeb</name>
    <title>Default Suite : AutoTestWeb</title>
    <test-cases>
        <test-case start="1530881401442" stop="1530881407400" status="failed">
            <name>loginAsExistingUser[Testing123@testmail.com]</name>
            <description>Registering a new user at Automation Practice</description>
            <failure>
                <message>ComparisonFailureWithCause: expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;</message>
                <stack-trace>expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;
	at Journey1.loginExistingUser.loginAsExistingUser(loginExistingUser.java:32)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="AutoTestWeb"/>
                <label name="testClass" value="Journey1.loginExistingUser"/>
                <label name="testMethod" value="loginAsExistingUser"/>
                <label name="testId" value="RegNew1"/>
                <label name="host" value="ISVGRELT0002689"/>
                <label name="thread" value="11400@ISVGRELT0002689.main(1)"/>
            </labels>
        </test-case>
        <test-case start="1530881410613" stop="1530881415647" status="failed">
            <name>loginAsExistingUser[s3cur3P4ssw0rd]</name>
            <description>Registering a new user at Automation Practice</description>
            <failure>
                <message>ComparisonFailureWithCause: expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;</message>
                <stack-trace>expected:&lt;[my account]&gt; but was:&lt;[authentication]&gt;
	at Journey1.loginExistingUser.loginAsExistingUser(loginExistingUser.java:32)
	at [[Reflective call: 4 frames collapsed (https://goo.gl/aH3UyP)]].(:0)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels>
                <label name="testSuite" value="Default Suite"/>
                <label name="testGroup" value="AutoTestWeb"/>
                <label name="testClass" value="Journey1.loginExistingUser"/>
                <label name="testMethod" value="loginAsExistingUser"/>
                <label name="testId" value="RegNew1"/>
                <label name="host" value="ISVGRELT0002689"/>
                <label name="thread" value="11400@ISVGRELT0002689.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
